### ISSUE TITLE
[discussion] Merging capabilities with other projects to get something new

### ISSUE THREAD

**Issue by archenroot** [jOOQ/jOOR#45]
Hi guys,

I like JOOQ and seing reflections done in similar way is nice. But we have multiple projects in the wild, why don't agree and create a new fully featured reflection advanced API for all?

https://github.com/ronmamo/reflections
and most promising - https://github.com/EsotericSoftware/reflectasm
https://github.com/Genymobile/mirror

maybe there are others. This idea came to my head after reading tweet by Adam Bien (java champion):
https://twitter.com/AdamBien/status/966279325178875904

To create a testing framework for java applications fully based on reflections. But this is quite big amount of work and requires as well unified reflection API. What do you think guys, is there a space for merging powers to build something which can be used or integrated into testing frameworks later?

I refer here creators of other frameworks to put their oppinions on this idea. I welcome any kind of response.

@EsotericSoftware - reflect asm
@ronmamo
@CaptainBern - behind unmaintained project https://github.com/CaptainBern/Reflection
@Genymobile
@AdamBien - autor behind the tweet with original idea

I think unification of thee reflection advanced API could be fist initiative behind greater idea to auto test any application.

**Comment by ooxi** [comment]
You get that Adam Bien‏ is joking, right?

**Comment by archenroot** [comment]
@ooxi  - Well yes and no, tests are big pain and using reflection to auto-generate test cases is not something unreal, there could be lot of cases where you can almost auto test without any kind of work.

Anyway the main discussion I wanted to open is about merging multiple projects doing reflection, each with other API available...

**Comment by lukaseder** [comment]
> But we have multiple projects in the wild, why don't agree and create a new fully featured reflection advanced API for all?

Welcome to the wonderful world of Java community open source, where we all respectfully agree to disagree and collectively suffer from NIH syndrome, which leads to tons of reinventions of wheels

> maybe there are others

At least a ton

> To create a testing framework for java applications fully based on reflections

You requesting this *here* is akin to someone going to a tyre manufacturer (reflection) and requesting they build cars (something random built on top of reflection)

> But this is quite big amount of work

I do understand you don't want to do it. I wouldn't want to, either.

> and requires as well unified reflection API

Good news for you! The JDK had a "unified" reflection API since version 1.0, and it is constantly improved and adapted to new Java features.

> What do you think guys, is there a space for merging powers to build something which can be used or integrated into testing frameworks later?

You're literally requesting *"quite big amount of work"* (notably, quite unrelated work) from someone who wrote a nice little, yet trivial, single-class reflection "framework" during a trainride from somewhere to somewhere more awesome.

> I welcome any kind of response.

I'm glad you do. Sometimes, my tone is misunderstood. I'm really a nice guy IRL

> I think unification of thee reflection advanced API could be fist initiative behind greater idea to auto test any application.

I'm really flattered that you call jOOR "advanced". Really.

But nope. Truth is, if someone actually did take Adam Bien seriously (e.g. you), they could just simply go ahead and build that super powerful, game changing tool on top of the JDK reflection APIs (really, it's just a silly loop over `Class.getMethods()`, and by chance, release yet another "improved reflection API" to compete with jOOR and the likes.

I wish you the best of luck.

Cheers,
Lukas (also Java Champion, since this seems to be relevant in the context of this discussion).

![f0dbe821-7ef2-4a23-ab58-626154ba7812](https://user-images.githubusercontent.com/734593/36644888-ef1b9b18-1a60-11e8-8d39-b6422220b2f1.gif)

**Comment by archenroot** [comment]
:-))) I also reinvent wheels, the idea is just about implementing unified reflection... but I see this doesn't make sense to discuss here :-)) good luck to you as well.

**Comment by lukaseder** [comment]
I don't disagree with you, but any approach that doesn't result in a JSR or even a JEP is meaningless.
